# Generated by Django 3.0.5 on 2020-11-24 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busBookingSystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bus_Destination',
            new_name='DestinationState',
        ),
    ]
