# Generated by Django 3.0.5 on 2020-11-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busBookingSystem', '0002_auto_20201124_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='statebus',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
